ALTER TABLE financial_2026 ADD COLUMN IF NOT EXISTS "直播日期" DATE;
ALTER TABLE financial_2026 ADD COLUMN IF NOT EXISTS "支付GMV" NUMERIC;
ALTER TABLE financial_2026 ADD COLUMN IF NOT EXISTS "支付绿色GMV" NUMERIC;
ALTER TABLE financial_2026 ADD COLUMN IF NOT EXISTS "T0绿色GMV" NUMERIC;
ALTER TABLE financial_2026 ADD COLUMN IF NOT EXISTS "预估结算GMV" NUMERIC;
ALTER TABLE financial_2026 ADD COLUMN IF NOT EXISTS "预估绿色结算GMV" NUMERIC;
ALTER TABLE financial_2026 ADD COLUMN IF NOT EXISTS "分销成本" NUMERIC;
ALTER TABLE financial_2026 ADD COLUMN IF NOT EXISTS "T0机构佣金" NUMERIC;;
