-- 用户配置表：存储跨会话持久化配置（如评分卡标准、GenBI 规则参数等）
-- 写操作通过 Edge Function（service_role）完成，RLS 仅控制直接 PostgREST 读
CREATE TABLE IF NOT EXISTS user_config (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL,
  config_key text NOT NULL,
  config_value jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(user_id, config_key)
);

COMMENT ON TABLE user_config IS '用户级别配置持久化，按 user_id + config_key 唯一索引';
COMMENT ON COLUMN user_config.user_id IS '用户标识（Feishu open_id 或 Supabase user id）';
COMMENT ON COLUMN user_config.config_key IS '配置键名（如 bs_score_config）';
COMMENT ON COLUMN user_config.config_value IS 'JSON 配置值';

-- 更新时自动刷新 updated_at
CREATE OR REPLACE FUNCTION update_user_config_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_user_config_updated_at
  BEFORE UPDATE ON user_config
  FOR EACH ROW
  EXECUTE FUNCTION update_user_config_updated_at();

-- RLS：已认证用户可读取自己的配置
ALTER TABLE user_config ENABLE ROW LEVEL SECURITY;

CREATE POLICY "读自己的配置" ON user_config
  FOR SELECT
  USING (auth.role() = 'authenticated');

-- 写操作通过 Edge Function（service_role）完成，不创建直接写入策略
